// Climas escolhidos antes da partida. Cada preset é só dado: o ambiente, o
// acampamento, o terreno, os braseiros e o áudio ambiente leem o que precisam.
//
// Campos:
//   background/fogColor/fogDensity  céu e névoa
//   light                           multiplicadores das luzes da cena
//   snow/rain/sand                  precipitação base (0..1)
//   lateRain                        a chuva gelada entra na reta final
//   wind                            força do vento (bandeiras, partículas, áudio)
//   lightning                       raios com trovão
//   darkness                        quão noturno é (braseiros pesam mais)
//   campVisibility                  quanto o acampamento ao fundo aparece
//   ground/terrainTint/snowCover    chão distante, tom e neve no terreno
export const WEATHERS = {
  neve: {
    id: 'neve',
    label: 'Neve',
    hint: 'Noite roxa de neve que engrossa conforme a batalha',
    background: 0x1a0f2e,
    fogColor: 0x3a2358,
    fogDensity: 0.045,
    light: { ambient: 1, hemi: 1, key: 1, fill: 1 },
    snow: 0.2,
    rain: 0,
    sand: 0,
    lateRain: true,
    wind: 0.35,
    lightning: false,
    darkness: 0.75,
    campVisibility: 0.85,
    campTint: 0x0f0a1a,
    ground: 0x2b2748,
    mounds: 0x3c3960,
    terrainTint: 0x857a86,
    snowCover: 0.4,
    dust: 0.4,
    groundFog: 1,
  },
  limpo: {
    id: 'limpo',
    label: 'Dia claro',
    hint: 'Céu aberto de fim de tarde: o acampamento inimigo à vista',
    background: 0x707c98,
    fogColor: 0x8c8fa4,
    fogDensity: 0.02,
    light: { ambient: 1.25, hemi: 1.45, key: 1.3, fill: 1.2 },
    snow: 0,
    rain: 0,
    sand: 0,
    lateRain: false,
    wind: 0.25,
    lightning: false,
    darkness: 0.15,
    campVisibility: 1,
    campTint: 0x3a3a4a,
    ground: 0x3f3b30,
    mounds: 0x4c473a,
    terrainTint: 0xb3a38a,
    snowCover: 0,
    dust: 0.55,
    groundFog: 0.35,
  },
  neblina: {
    id: 'neblina',
    label: 'Neblina',
    hint: 'Bruma espessa: o inimigo é só sombra ao longe',
    background: 0x2b2a35,
    fogColor: 0x575563,
    fogDensity: 0.075,
    light: { ambient: 0.9, hemi: 0.85, key: 0.7, fill: 0.9 },
    snow: 0,
    rain: 0,
    sand: 0,
    lateRain: false,
    wind: 0.1,
    lightning: false,
    darkness: 0.5,
    campVisibility: 0.45,
    campTint: 0x2a2933,
    ground: 0x33313b,
    mounds: 0x3e3c47,
    terrainTint: 0x8d8a92,
    snowCover: 0.05,
    dust: 0.25,
    groundFog: 2.2,
  },
  tempestade: {
    id: 'tempestade',
    label: 'Tempestade',
    hint: 'Chuva pesada, vento e raios que revelam o acampamento',
    background: 0x0b0c15,
    fogColor: 0x1c1f2e,
    fogDensity: 0.05,
    light: { ambient: 0.65, hemi: 0.6, key: 0.55, fill: 0.7 },
    snow: 0,
    rain: 0.85,
    sand: 0,
    lateRain: false,
    wind: 0.85,
    lightning: true,
    darkness: 0.95,
    campVisibility: 0.55,
    campTint: 0x07080d,
    ground: 0x1c1d26,
    mounds: 0x262833,
    terrainTint: 0x6c6a72,
    snowCover: 0,
    dust: 0.1,
    groundFog: 1.2,
  },
  areia: {
    id: 'areia',
    label: 'Tempestade de areia',
    hint: 'Vento seco e areia no ar: tudo vira silhueta ocre',
    background: 0x5a3b21,
    fogColor: 0x96673a,
    fogDensity: 0.06,
    light: { ambient: 1.05, hemi: 0.95, key: 0.8, fill: 1 },
    snow: 0,
    rain: 0,
    sand: 1,
    lateRain: false,
    wind: 1,
    lightning: false,
    darkness: 0.35,
    campVisibility: 0.55,
    campTint: 0x3a2412,
    ground: 0x5e4630,
    mounds: 0x6e553a,
    terrainTint: 0xc29a6a,
    snowCover: 0,
    dust: 0.15,
    groundFog: 0.6,
  },
};

export const WEATHER_ORDER = ['neve', 'limpo', 'neblina', 'tempestade', 'areia'];

export function getWeather(id) {
  return WEATHERS[id] ?? WEATHERS.neve;
}
